version: '3.7'

services:
  server:
    volumes:
      - static:/static
    build:
      context: ./server
    ports:
      - "8000:8000"
  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
    volumes:
      - frontend:/app/build
  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  static:
  frontend: